
package com.his.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "WebServices", targetNamespace = "http://server.his.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface WebServices {


    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "failureDoctor", targetNamespace = "http://server.his.com/", className = "com.his.server.FailureDoctor")
    @ResponseWrapper(localName = "failureDoctorResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.FailureDoctorResponse")
    public String failureDoctor(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEvaluateRegister", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateEvaluateRegister")
    @ResponseWrapper(localName = "updateEvaluateRegisterResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateEvaluateRegisterResponse")
    public int updateEvaluateRegister(
            @WebParam(name = "arg0", targetNamespace = "")
                    Evaluate arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findfailureDoctor", targetNamespace = "http://server.his.com/", className = "com.his.server.FindfailureDoctor")
    @ResponseWrapper(localName = "findfailureDoctorResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.FindfailureDoctorResponse")
    public String findfailureDoctor(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openPrescription", targetNamespace = "http://server.his.com/", className = "com.his.server.OpenPrescription")
    @ResponseWrapper(localName = "openPrescriptionResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.OpenPrescriptionResponse")
    public String openPrescription(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    List<PatientCheck> arg2);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClinicNo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetClinicNo")
    @ResponseWrapper(localName = "getClinicNoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetClinicNoResponse")
    public String getClinicNo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBeforeOneDrugNoPay", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneDrugNoPay")
    @ResponseWrapper(localName = "getBeforeOneDrugNoPayResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneDrugNoPayResponse")
    public String getBeforeOneDrugNoPay(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getChineseMedicine", targetNamespace = "http://server.his.com/", className = "com.his.server.GetChineseMedicine")
    @ResponseWrapper(localName = "getChineseMedicineResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetChineseMedicineResponse")
    public String getChineseMedicine(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorSourceInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorSourceInfo")
    @ResponseWrapper(localName = "getDoctorSourceInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorSourceInfoResponse")
    public String getDoctorSourceInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertPatientAssay", targetNamespace = "http://server.his.com/", className = "com.his.server.InsertPatientAssay")
    @ResponseWrapper(localName = "insertPatientAssayResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.InsertPatientAssayResponse")
    public String insertPatientAssay(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Assay> arg1);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssayResult", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayResult")
    @ResponseWrapper(localName = "getAssayResultResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayResultResponse")
    public String getAssayResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRegisterOrders", targetNamespace = "http://server.his.com/", className = "com.his.server.FindRegisterOrders")
    @ResponseWrapper(localName = "findRegisterOrdersResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.FindRegisterOrdersResponse")
    public String findRegisterOrders(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPatientRegisHistoryInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetPatientRegisHistoryInfo")
    @ResponseWrapper(localName = "getPatientRegisHistoryInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetPatientRegisHistoryInfoResponse")
    public String getPatientRegisHistoryInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardno", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCardno")
    @ResponseWrapper(localName = "getCardnoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCardnoResponse")
    public String getCardno(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutpOrder", targetNamespace = "http://server.his.com/", className = "com.his.server.GetOutpOrder")
    @ResponseWrapper(localName = "getOutpOrderResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetOutpOrderResponse")
    public String getOutpOrder();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptDict", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptDict")
    @ResponseWrapper(localName = "getDeptDictResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptDictResponse")
    public String getDeptDict(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regularRegisterRefund", targetNamespace = "http://server.his.com/", className = "com.his.server.RegularRegisterRefund")
    @ResponseWrapper(localName = "regularRegisterRefundResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.RegularRegisterRefundResponse")
    public String regularRegisterRefund(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<PatientRegister> arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDrug", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrug")
    @ResponseWrapper(localName = "getDrugResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrugResponse")
    public String getDrug(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doctorAndPatientLoginChange", targetNamespace = "http://server.his.com/", className = "com.his.server.DoctorAndPatientLoginChange")
    @ResponseWrapper(localName = "doctorAndPatientLoginChangeResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.DoctorAndPatientLoginChangeResponse")
    public String doctorAndPatientLoginChange(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAppointmentRegistInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAppointmentRegistInfo")
    @ResponseWrapper(localName = "getAppointmentRegistInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAppointmentRegistInfoResponse")
    public String getAppointmentRegistInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssayResultTakeNotes", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayResultTakeNotes")
    @ResponseWrapper(localName = "getAssayResultTakeNotesResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayResultTakeNotesResponse")
    public String getAssayResultTakeNotes(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    int arg2);

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardCount", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCardCount")
    @ResponseWrapper(localName = "getCardCountResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCardCountResponse")
    public int getCardCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorVisitStatus", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorVisitStatus")
    @ResponseWrapper(localName = "getDoctorVisitStatusResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorVisitStatusResponse")
    public String getDoctorVisitStatus(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findLeft", targetNamespace = "http://server.his.com/", className = "com.his.server.FindLeft")
    @ResponseWrapper(localName = "findLeftResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.FindLeftResponse")
    public String findLeft();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptNameByDeptcode", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptNameByDeptcode")
    @ResponseWrapper(localName = "getDeptNameByDeptcodeResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptNameByDeptcodeResponse")
    public String getDeptNameByDeptcode(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDoctor", targetNamespace = "http://server.his.com/", className = "com.his.server.FindDoctor")
    @ResponseWrapper(localName = "findDoctorResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.FindDoctorResponse")
    public String findDoctor(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCardno", targetNamespace = "http://server.his.com/", className = "com.his.server.AddCardno")
    @ResponseWrapper(localName = "addCardnoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.AddCardnoResponse")
    public int addCardno(
            @WebParam(name = "arg0", targetNamespace = "")
                    Patients arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBeforeOneAssayNoPay", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneAssayNoPay")
    @ResponseWrapper(localName = "getBeforeOneAssayNoPayResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneAssayNoPayResponse")
    public String getBeforeOneAssayNoPay(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDrugUsage", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrugUsage")
    @ResponseWrapper(localName = "getDrugUsageResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrugUsageResponse")
    public String getDrugUsage();

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssayClass", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayClass")
    @ResponseWrapper(localName = "getAssayClassResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssayClassResponse")
    public String getAssayClass();

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicalrecordAll", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMedicalrecordAll")
    @ResponseWrapper(localName = "getMedicalrecordAllResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMedicalrecordAllResponse")
    public String getMedicalrecordAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    int arg2);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicalLast", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMedicalLast")
    @ResponseWrapper(localName = "getMedicalLastResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMedicalLastResponse")
    public String getMedicalLast(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisterCanRefundPatients", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRegisterCanRefundPatients")
    @ResponseWrapper(localName = "getRegisterCanRefundPatientsResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRegisterCanRefundPatientsResponse")
    public String getRegisterCanRefundPatients();

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getExamNoSeq", targetNamespace = "http://server.his.com/", className = "com.his.server.GetExamNoSeq")
    @ResponseWrapper(localName = "getExamNoSeqResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetExamNoSeqResponse")
    public String getExamNoSeq();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delPrescribing", targetNamespace = "http://server.his.com/", className = "com.his.server.DelPrescribing")
    @ResponseWrapper(localName = "delPrescribingResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.DelPrescribingResponse")
    public String delPrescribing(
            @WebParam(name = "arg0", targetNamespace = "")
                    Prescription arg0);

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://server.his.com/", className = "com.his.server.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.RegisterResponse")
    public int register(
            @WebParam(name = "arg0", targetNamespace = "")
                    PatientRegister arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://server.his.com/", className = "com.his.server.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetValueResponse")
    public String getValue();

    /**
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckOrChemical", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckOrChemical")
    @ResponseWrapper(localName = "getCheckOrChemicalResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckOrChemicalResponse")
    public String getCheckOrChemical(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
                    int arg5);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPrescription", targetNamespace = "http://server.his.com/", className = "com.his.server.AddPrescription")
    @ResponseWrapper(localName = "addPrescriptionResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.AddPrescriptionResponse")
    public String addPrescription(
            @WebParam(name = "arg0", targetNamespace = "")
                    Prescription arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "beInHospital", targetNamespace = "http://server.his.com/", className = "com.his.server.BeInHospital")
    @ResponseWrapper(localName = "beInHospitalResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.BeInHospitalResponse")
    public String beInHospital(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doctorVisitStatusManager", targetNamespace = "http://server.his.com/", className = "com.his.server.DoctorVisitStatusManager")
    @ResponseWrapper(localName = "doctorVisitStatusManagerResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.DoctorVisitStatusManagerResponse")
    public String doctorVisitStatusManager();

    /**
     * @param arg1
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemsSum", targetNamespace = "http://server.his.com/", className = "com.his.server.GetItemsSum")
    @ResponseWrapper(localName = "getItemsSumResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetItemsSumResponse")
    public int getItemsSum(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutpMrDiagDesc", targetNamespace = "http://server.his.com/", className = "com.his.server.GetOutpMrDiagDesc")
    @ResponseWrapper(localName = "getOutpMrDiagDescResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetOutpMrDiagDescResponse")
    public String getOutpMrDiagDesc(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTheSameDayMedicalrecordAll", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTheSameDayMedicalrecordAll")
    @ResponseWrapper(localName = "getTheSameDayMedicalrecordAllResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTheSameDayMedicalrecordAllResponse")
    public String getTheSameDayMedicalrecordAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckClass", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckClass")
    @ResponseWrapper(localName = "getCheckClassResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckClassResponse")
    public String getCheckClass();

    /**
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipeList", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRecipeList")
    @ResponseWrapper(localName = "getRecipeListResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRecipeListResponse")
    public String getRecipeList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    int arg4);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delAssayItem", targetNamespace = "http://server.his.com/", className = "com.his.server.DelAssayItem")
    @ResponseWrapper(localName = "delAssayItemResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.DelAssayItemResponse")
    public String delAssayItem(
            @WebParam(name = "arg0", targetNamespace = "")
                    Assay arg0);

    /**
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTreatChargeInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTreatChargeInfo")
    @ResponseWrapper(localName = "getTreatChargeInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTreatChargeInfoResponse")
    public String getTreatChargeInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    int arg4);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDoctorVisitStatus", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateDoctorVisitStatus")
    @ResponseWrapper(localName = "updateDoctorVisitStatusResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateDoctorVisitStatusResponse")
    public String updateDoctorVisitStatus(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBeforeOneCheckNoPay", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneCheckNoPay")
    @ResponseWrapper(localName = "getBeforeOneCheckNoPayResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetBeforeOneCheckNoPayResponse")
    public String getBeforeOneCheckNoPay(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDoctorInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateDoctorInfo")
    @ResponseWrapper(localName = "updateDoctorInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateDoctorInfoResponse")
    public String updateDoctorInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegisterNumberAndLastTimeAndNumber", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRegisterNumberAndLastTimeAndNumber")
    @ResponseWrapper(localName = "getRegisterNumberAndLastTimeAndNumberResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetRegisterNumberAndLastTimeAndNumberResponse")
    public String getRegisterNumberAndLastTimeAndNumber(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCheckResult", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckResult")
    @ResponseWrapper(localName = "getCheckResultResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetCheckResultResponse")
    public String getCheckResult(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    int arg2);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorLogin", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorLogin")
    @ResponseWrapper(localName = "getDoctorLoginResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorLoginResponse")
    public String getDoctorLogin(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMakeUpPrescribe", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMakeUpPrescribe")
    @ResponseWrapper(localName = "getMakeUpPrescribeResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetMakeUpPrescribeResponse")
    public String getMakeUpPrescribe(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVisitNo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetVisitNo")
    @ResponseWrapper(localName = "getVisitNoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetVisitNoResponse")
    public String getVisitNo();

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWestern", targetNamespace = "http://server.his.com/", className = "com.his.server.GetWestern")
    @ResponseWrapper(localName = "getWesternResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetWesternResponse")
    public String getWestern();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertMedicalrecord", targetNamespace = "http://server.his.com/", className = "com.his.server.InsertMedicalrecord")
    @ResponseWrapper(localName = "insertMedicalrecordResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.InsertMedicalrecordResponse")
    public String insertMedicalrecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    Medicalrecord arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDeptName", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptName")
    @ResponseWrapper(localName = "getDeptNameResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDeptNameResponse")
    public String getDeptName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "seekedDoctor", targetNamespace = "http://server.his.com/", className = "com.his.server.SeekedDoctor")
    @ResponseWrapper(localName = "seekedDoctorResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.SeekedDoctorResponse")
    public String seekedDoctor(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntryname", targetNamespace = "http://server.his.com/", className = "com.his.server.GetEntryname")
    @ResponseWrapper(localName = "getEntrynameResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetEntrynameResponse")
    public String getEntryname(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTheSameDayOutpMr", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTheSameDayOutpMr")
    @ResponseWrapper(localName = "getTheSameDayOutpMrResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTheSameDayOutpMrResponse")
    public String getTheSameDayOutpMr(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTestNo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTestNo")
    @ResponseWrapper(localName = "getTestNoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetTestNoResponse")
    public String getTestNo();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delCheckItem", targetNamespace = "http://server.his.com/", className = "com.his.server.DelCheckItem")
    @ResponseWrapper(localName = "delCheckItemResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.DelCheckItemResponse")
    public String delCheckItem(
            @WebParam(name = "arg0", targetNamespace = "")
                    PatientCheck arg0);

    /**
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssaySecondClass", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssaySecondClass")
    @ResponseWrapper(localName = "getAssaySecondClassResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetAssaySecondClassResponse")
    public String getAssaySecondClass(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateMedicalrecord", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateMedicalrecord")
    @ResponseWrapper(localName = "updateMedicalrecordResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.UpdateMedicalrecordResponse")
    public String updateMedicalrecord(
            @WebParam(name = "arg0", targetNamespace = "")
                    Medicalrecord arg0);

    /**
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDrugDosage", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrugDosage")
    @ResponseWrapper(localName = "getDrugDosageResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDrugDosageResponse")
    public String getDrugDosage();

    /**
     * @param arg0
     * @return returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cacleRegsiter", targetNamespace = "http://server.his.com/", className = "com.his.server.CacleRegsiter")
    @ResponseWrapper(localName = "cacleRegsiterResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.CacleRegsiterResponse")
    public int cacleRegsiter(
            @WebParam(name = "arg0", targetNamespace = "")
                    PatientRegister arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorInfo", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorInfo")
    @ResponseWrapper(localName = "getDoctorInfoResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetDoctorInfoResponse")
    public String getDoctorInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSubclass", targetNamespace = "http://server.his.com/", className = "com.his.server.GetSubclass")
    @ResponseWrapper(localName = "getSubclassResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.GetSubclassResponse")
    public String getSubclass(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerRefundWx", targetNamespace = "http://server.his.com/", className = "com.his.server.RegisterRefundWx")
    @ResponseWrapper(localName = "registerRefundWxResponse", targetNamespace = "http://server.his.com/", className = "com.his.server.RegisterRefundWxResponse")
    public String registerRefundWx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

}
