
package org.tempurl;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "n_webserviceSoap", targetNamespace = "http://tempurl.org")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface NWebserviceSoap {


    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/histest")
    @WebResult(name = "histestResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "histest", targetNamespace = "http://tempurl.org", className = "org.tempurl.Histest")
    @ResponseWrapper(localName = "histestResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.HistestResponse")
    public String histest(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getpatientinfo")
    @WebResult(name = "getpatientinfoResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getpatientinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getpatientinfo")
    @ResponseWrapper(localName = "getpatientinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetpatientinfoResponse")
    public String getpatientinfo(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/checkidcard")
    @WebResult(name = "checkidcardResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "checkidcard", targetNamespace = "http://tempurl.org", className = "org.tempurl.Checkidcard")
    @ResponseWrapper(localName = "checkidcardResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.CheckidcardResponse")
    public String checkidcard(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/registpatientinfo")
    @WebResult(name = "registpatientinfoResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "registpatientinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.Registpatientinfo")
    @ResponseWrapper(localName = "registpatientinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.RegistpatientinfoResponse")
    public String registpatientinfo(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/cancelregpatientinfo")
    @WebResult(name = "cancelregpatientinfoResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "cancelregpatientinfo", targetNamespace = "http://tempurl.org", className = "org.tempurl.Cancelregpatientinfo")
    @ResponseWrapper(localName = "cancelregpatientinfoResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.CancelregpatientinfoResponse")
    public String cancelregpatientinfo(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/recharge")
    @WebResult(name = "rechargeResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "recharge", targetNamespace = "http://tempurl.org", className = "org.tempurl.Recharge")
    @ResponseWrapper(localName = "rechargeResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.RechargeResponse")
    public String recharge(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/hosaccountpay")
    @WebResult(name = "hosaccountpayResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "hosaccountpay", targetNamespace = "http://tempurl.org", className = "org.tempurl.Hosaccountpay")
    @ResponseWrapper(localName = "hosaccountpayResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.HosaccountpayResponse")
    public String hosaccountpay(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/notifyresultforpay")
    @WebResult(name = "notifyresultforpayResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "notifyresultforpay", targetNamespace = "http://tempurl.org", className = "org.tempurl.Notifyresultforpay")
    @ResponseWrapper(localName = "notifyresultforpayResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.NotifyresultforpayResponse")
    public String notifyresultforpay(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getregtypelist")
    @WebResult(name = "getregtypelistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getregtypelist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getregtypelist")
    @ResponseWrapper(localName = "getregtypelistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetregtypelistResponse")
    public String getregtypelist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getregdeptlist")
    @WebResult(name = "getregdeptlistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getregdeptlist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getregdeptlist")
    @ResponseWrapper(localName = "getregdeptlistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetregdeptlistResponse")
    public String getregdeptlist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getregdoctlist")
    @WebResult(name = "getregdoctlistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getregdoctlist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getregdoctlist")
    @ResponseWrapper(localName = "getregdoctlistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetregdoctlistResponse")
    public String getregdoctlist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/lockregist")
    @WebResult(name = "lockregistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "lockregist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Lockregist")
    @ResponseWrapper(localName = "lockregistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.LockregistResponse")
    public String lockregist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/unlockregist")
    @WebResult(name = "unlockregistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "unlockregist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Unlockregist")
    @ResponseWrapper(localName = "unlockregistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UnlockregistResponse")
    public String unlockregist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/exeregist")
    @WebResult(name = "exeregistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "exeregist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Exeregist")
    @ResponseWrapper(localName = "exeregistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.ExeregistResponse")
    public String exeregist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getvisitreclist")
    @WebResult(name = "getvisitreclistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getvisitreclist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getvisitreclist")
    @ResponseWrapper(localName = "getvisitreclistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetvisitreclistResponse")
    public String getvisitreclist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "uf_get_prepayment_rcpt", action = "http://tempurl.org/uf_get_prepayment_rcpt")
    @WebResult(name = "uf_get_prepayment_rcptResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_get_prepayment_rcpt", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetPrepaymentRcpt")
    @ResponseWrapper(localName = "uf_get_prepayment_rcptResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetPrepaymentRcptResponse")
    public String ufGetPrepaymentRcpt();

    /**
     * @param asMsg
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "uf_error_return", action = "http://tempurl.org/uf_error_return")
    @WebResult(name = "uf_error_returnResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_error_return", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfErrorReturn")
    @ResponseWrapper(localName = "uf_error_returnResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfErrorReturnResponse")
    public String ufErrorReturn(
            @WebParam(name = "as_msg", targetNamespace = "http://tempurl.org")
                    String asMsg);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getrecipelist")
    @WebResult(name = "getrecipelistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getrecipelist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getrecipelist")
    @ResponseWrapper(localName = "getrecipelistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetrecipelistResponse")
    public String getrecipelist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/paybilltrade")
    @WebResult(name = "paybilltradeResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "paybilltrade", targetNamespace = "http://tempurl.org", className = "org.tempurl.Paybilltrade")
    @ResponseWrapper(localName = "paybilltradeResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.PaybilltradeResponse")
    public String paybilltrade(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asReturn
     */
    @WebMethod(operationName = "uf_get_rcpt_no", action = "http://tempurl.org/uf_get_rcpt_no")
    @RequestWrapper(localName = "uf_get_rcpt_no", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetRcptNo")
    @ResponseWrapper(localName = "uf_get_rcpt_noResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetRcptNoResponse")
    public void ufGetRcptNo(
            @WebParam(name = "as_return", targetNamespace = "http://tempurl.org", mode = WebParam.Mode.INOUT)
                    Holder<String> asReturn);

    /**
     * @param asReturn
     */
    @WebMethod(operationName = "uf_get_print", action = "http://tempurl.org/uf_get_print")
    @RequestWrapper(localName = "uf_get_print", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetPrint")
    @ResponseWrapper(localName = "uf_get_printResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfGetPrintResponse")
    public void ufGetPrint(
            @WebParam(name = "as_return", targetNamespace = "http://tempurl.org")
                    String asReturn);

    /**
     * @param ufOutpPayResult
     * @param asPid
     * @param adeMoney
     * @param adePayMoney
     * @param asSettleNo
     */
    @WebMethod(operationName = "uf_outp_pay", action = "http://tempurl.org/uf_outp_pay")
    @RequestWrapper(localName = "uf_outp_pay", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfOutpPay")
    @ResponseWrapper(localName = "uf_outp_payResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfOutpPayResponse")
    public void ufOutpPay(
            @WebParam(name = "as_pid", targetNamespace = "http://tempurl.org")
                    String asPid,
            @WebParam(name = "ade_money", targetNamespace = "http://tempurl.org")
                    BigDecimal adeMoney,
            @WebParam(name = "ade_pay_money", targetNamespace = "http://tempurl.org", mode = WebParam.Mode.INOUT)
                    Holder<BigDecimal> adePayMoney,
            @WebParam(name = "as_settle_no", targetNamespace = "http://tempurl.org")
                    String asSettleNo,
            @WebParam(name = "uf_outp_payResult", targetNamespace = "http://tempurl.org", mode = WebParam.Mode.OUT)
                    Holder<Short> ufOutpPayResult);

    /**
     *
     */
    @WebMethod(operationName = "uf_connect", action = "http://tempurl.org/uf_connect")
    @RequestWrapper(localName = "uf_connect", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfConnect")
    @ResponseWrapper(localName = "uf_connectResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfConnectResponse")
    public void ufConnect();

    /**
     *
     */
    @WebMethod(operationName = "uf_disconnect", action = "http://tempurl.org/uf_disconnect")
    @RequestWrapper(localName = "uf_disconnect", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfDisconnect")
    @ResponseWrapper(localName = "uf_disconnectResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfDisconnectResponse")
    public void ufDisconnect();

    /**
     * @param asPatientid
     * @param asMoney
     * @return returns java.lang.Short
     */
    @WebMethod(operationName = "uf_prepayment", action = "http://tempurl.org/uf_prepayment")
    @WebResult(name = "uf_prepaymentResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "uf_prepayment", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfPrepayment")
    @ResponseWrapper(localName = "uf_prepaymentResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.UfPrepaymentResponse")
    public Short ufPrepayment(
            @WebParam(name = "as_patientid", targetNamespace = "http://tempurl.org")
                    String asPatientid,
            @WebParam(name = "as_money", targetNamespace = "http://tempurl.org")
                    String asMoney);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getordertypelist")
    @WebResult(name = "getordertypelistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getordertypelist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getordertypelist")
    @ResponseWrapper(localName = "getordertypelistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetordertypelistResponse")
    public String getordertypelist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getorderdeptlist")
    @WebResult(name = "getorderdeptlistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getorderdeptlist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getorderdeptlist")
    @ResponseWrapper(localName = "getorderdeptlistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetorderdeptlistResponse")
    public String getorderdeptlist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getorderdatelist")
    @WebResult(name = "getorderdatelistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getorderdatelist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getorderdatelist")
    @ResponseWrapper(localName = "getorderdatelistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetorderdatelistResponse")
    public String getorderdatelist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getorderdoctlist")
    @WebResult(name = "getorderdoctlistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getorderdoctlist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getorderdoctlist")
    @ResponseWrapper(localName = "getorderdoctlistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetorderdoctlistResponse")
    public String getorderdoctlist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/execorderreg")
    @WebResult(name = "execorderregResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "execorderreg", targetNamespace = "http://tempurl.org", className = "org.tempurl.Execorderreg")
    @ResponseWrapper(localName = "execorderregResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.ExecorderregResponse")
    public String execorderreg(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/getorderlist")
    @WebResult(name = "getorderlistResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "getorderlist", targetNamespace = "http://tempurl.org", className = "org.tempurl.Getorderlist")
    @ResponseWrapper(localName = "getorderlistResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.GetorderlistResponse")
    public String getorderlist(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/execgetorderreg")
    @WebResult(name = "execgetorderregResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "execgetorderreg", targetNamespace = "http://tempurl.org", className = "org.tempurl.Execgetorderreg")
    @ResponseWrapper(localName = "execgetorderregResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.ExecgetorderregResponse")
    public String execgetorderreg(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/cancelorderreg")
    @WebResult(name = "cancelorderregResult", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "cancelorderreg", targetNamespace = "http://tempurl.org", className = "org.tempurl.Cancelorderreg")
    @ResponseWrapper(localName = "cancelorderregResponse", targetNamespace = "http://tempurl.org", className = "org.tempurl.CancelorderregResponse")
    public String cancelorderreg(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

    /**
     * @param asInput
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://tempurl.org/paybilltrade1")
    @WebResult(name = "paybilltrade1Result", targetNamespace = "http://tempurl.org")
    @RequestWrapper(localName = "paybilltrade1", targetNamespace = "http://tempurl.org", className = "org.tempurl.Paybilltrade1")
    @ResponseWrapper(localName = "paybilltrade1Response", targetNamespace = "http://tempurl.org", className = "org.tempurl.Paybilltrade1Response")
    public String paybilltrade1(
            @WebParam(name = "as_input", targetNamespace = "http://tempurl.org")
                    String asInput);

}
